-- 生成15篇游记数据
INSERT INTO note_post (user_id, title, content, topic_ids, cover, view_count, like_count, comment_count, status, audit_status, create_time, update_time) VALUES
(1, 'Terraced fields at sunrise', 'Standing at the highest point of the Miao village terraced fields, watching the sunrise spread gold across the entire hillside. Layer upon layer of terraced fields shimmering in the morning light, like earth brocade. Every visit feels different. This time was taken in the mist, the terraced fields appearing and disappearing, more mysterious and dreamlike.', JSON_ARRAY(17), 'http://localhost:3000/src/views/community/topics_photos/苗寨梯田风光.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(2, 'Craftsmans silver art', 'Watching the elderly craftsman forge silver jewelry in the Miao workshop, each hammer strike echoing the soul of the Miao people. From melting silver to forging to fine engraving, a piece of jewelry takes anywhere from three days to half a month. Watching their hands dance on the silver, that is true art.', JSON_ARRAY(18), 'http://localhost:3000/src/views/community/topics_photos/苗族银饰锻造.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(3, 'Long table feast', 'More than twenty dishes lined the long table, from pickled wild vegetables to freshly killed free-range chicken, each dish a masterpiece from Miao aunties. Most memorable was sitting across from father, everyone raising glasses together. One meal brought out the feeling of home.', JSON_ARRAY(19), 'http://localhost:3000/src/views/community/topics_photos/苗家长桌宴.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(4, 'Batik and embroidery', 'Ancient batik techniques are perfectly preserved here. Using beeswax to paint on cloth, then soaking in indigo dye, after washing away the wax, ice crack patterns emerge. Every batik cloth is a unique work of art, carrying the love of the Miao people for life.', JSON_ARRAY(20), 'http://localhost:3000/src/views/community/topics_photos/蜡染与苗绣.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(5, 'Miao year celebration', 'Miao year is the most grand festival for the Miao people, drums boom through the valley, young people in traditional costumes dance freely. Eating glutinous rice cakes, drinking rice wine, celebrating harvest and reunion with clan members. At this moment, time seems to stand still.', JSON_ARRAY(21), 'http://localhost:3000/src/views/community/topics_photos/苗年节庆.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(1, 'Sour fish soup memories', 'Sour soup is the soul of Guizhou, simmered from tomatoes and peppers with a tangy and appetizing taste. Fresh fish tumbles in the soup, absorbing its essence. Biting down, the fish is tender and fresh, the sour soup taste blooming in the mouth. This is the taste of Guizhou.', JSON_ARRAY(22), 'https://source.unsplash.com/800x600/?soup,fish', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(2, 'Stories from stilt houses', 'Wooden stilt houses suspended on cliff edges, with endless mountain valleys below. Standing on the upper floor looking out, the entire village lies before your eyes. The wisdom and beauty of this architecture can only be truly understood through personal experience.', JSON_ARRAY(23), 'http://localhost:3000/src/views/community/topics_photos/吊脚楼建筑.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(3, 'Lusheng dance ancient rhythm', 'When the lusheng sounds, young people jump into the ancient dance. Feet tapping the rhythm, bodies swaying with the music, this is the joy passed down through generations of Miao people.', JSON_ARRAY(24), 'http://localhost:3000/src/views/community/topics_photos/芦笙舞与飞歌.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(4, 'Wearing Miao costume', 'Every piece of Miao clothing tells a story. Silver ornaments weigh heavy on the shoulders, colorful fabric clings to the body, wearing embroidered hats, the whole person shines. This is the pride of the Miao people.', JSON_ARRAY(25), 'http://localhost:3000/src/views/community/topics_photos/苗族服饰搭配.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(5, 'Miao medicine and herbs', 'Entering the Miao medical clinic, watching the doctor treat patients using traditional methods. Those herbs, that ancient medicine, still shine brightly here. The best doctor is nature itself.', JSON_ARRAY(26), 'http://localhost:3000/src/views/community/topics_photos/苗医苗药探秘.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(1, 'Slow life in Udong village', 'No city noise in the village, only bird calls and wind sounds. Walking along the mountain path, watching farmers work in the fields, this is the most authentic Guizhou.', JSON_ARRAY(27), 'https://source.unsplash.com/800x600/?village,rural', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(2, 'Ancient tea trees', 'Hundred-year-old tea trees have witnessed countless years of change. Tea-picking sisters sing ancient tea-picking songs under the trees. The tea here is fragrant, one sip tastes like the wilderness.', JSON_ARRAY(28), 'https://source.unsplash.com/800x600/?tea,ancient', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(3, 'Drum festival ceremony', 'The entire village is busy preparing for the drum festival, killing pigs and cattle, preparing tributes to ancestors. When the drums sound, the whole village kneels, at this moment I truly felt what faith means.', JSON_ARRAY(29), 'https://source.unsplash.com/800x600/?festival,ritual', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(4, 'Soul of village handicrafts', 'Bamboo weaving, wood carving, silver jewelry, each piece is the crystallization of decades of craftsmanship. Buying one home is like buying a piece of Miao history.', JSON_ARRAY(30), 'https://source.unsplash.com/800x600/?handicraft,art', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(5, 'Folk photography journey', 'Recording Miao daily life with a camera, capturing their smiles, labor and celebrations. Each photo is a story, every story deserves to be remembered.', JSON_ARRAY(31), 'https://source.unsplash.com/800x600/?photography,portrait', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW());

INSERT INTO note_post_image (post_id, image_url, sort, create_time, update_time)
SELECT id, cover, 1, NOW(), NOW() FROM note_post WHERE id > (SELECT MAX(id) - 15 FROM note_post);
