-- 生成15篇游记数据
INSERT INTO note_post (user_id, title, content, topic_ids, cover, view_count, like_count, comment_count, status, audit_status, create_time, update_time) VALUES
(1, '清晨五点的梯田，美到窒息', '站在苗寨梯田的最高处，看日出把金色洒满整个山坡。层层叠叠的梯田在晨光下闪闪发光，仿佛是大地的锦缎。来过很多次，每次都有不同的感受。这次是在雾气中拍摄的，梯田若隐若现，更显得神秘而梦幻。', JSON_ARRAY(17), 'http://localhost:3000/src/views/community/topics_photos/苗寨梯田风光.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(2, '匠人手中的银之诗', '在苗族手工坊里看阿爷打造银饰，每一锤都敲出了苗族人的灵魂。从熔银到锻造，再到精雕细琢，一件银饰要经过少则三天多则半个月。看着他们的手在银饰上舞动，那才叫真正的艺术。', JSON_ARRAY(18), 'http://localhost:3000/src/views/community/topics_photos/苗族银饰锻造.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(3, '苗家长桌宴，一席千般滋味', '二十多道菜摆满了整张长桌，从腌制的野菜到现杀的土鸡，每一道都是苗族阿姆的手艺。最难忘的是坐在阿爸对面，大家举杯共饮的那一刻。一顿饭吃出了家的感觉。', JSON_ARRAY(19), 'http://localhost:3000/src/views/community/topics_photos/苗家长桌宴.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(4, '蜡染的前世今生', '古老的蜡染技艺在这里得到完美传承。用蜂蜡在布料上作画，然后放入靛蓝染料中浸泡，蜡被洗去后，冰纹花纹就呈现出来了。每一块蜡染布都是独一无二的艺术品，承载着苗族人对生活的热爱。', JSON_ARRAY(20), 'http://localhost:3000/src/views/community/topics_photos/蜡染与苗绣.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(5, '苗年到，欢乐来', '苗年是苗族人最隆重的节日，鼓声咚咚咚响彻山谷，年轻人穿着传统服饰尽情舞蹈。吃着年糕，喝着米酒，和族人一起庆祝丰收和团圆。这一刻，时间仿佛静止了。', JSON_ARRAY(21), 'http://localhost:3000/src/views/community/topics_photos/苗年节庆.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(1, '一碗酸汤鱼，一生的记忆', '酸汤是贵州的灵魂，用番茄和辣椒熬成的汤底酸爽开胃。新鲜的鱼在汤里翻滚，吸收了汤的精华。咬下去，鱼肉鲜嫩，酸汤的味道在口腔里绽放。这就是贵州的味道。', JSON_ARRAY(22), 'https://source.unsplash.com/800x600/?sour-soup,fish', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(2, '吊脚楼上的故事', '木质的吊脚楼悬在悬崖边，下面是深不见底的山谷。站在楼上望出去，整个村寨尽在眼下。这种建筑的智慧和美学，只有亲身去体验才能明白。', JSON_ARRAY(23), 'http://localhost:3000/src/views/community/topics_photos/吊脚楼建筑.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(3, '芦笙舞动的古老节奏', '芦笙的声音一响起，年轻人就跳起了古老的舞蹈。脚步踏着节奏，身体随着音乐摇晃，这是苗族人祖祖辈辈传承下来的快乐。', JSON_ARRAY(24), 'http://localhost:3000/src/views/community/topics_photos/芦笙舞与飞歌.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(4, '穿上苗服，我就是苗族人', '每一件苗族服饰都讲述着一个故事。银饰沉甸甸地压在肩头，色彩艳丽的布料贴在身上，戴上绣花帽，整个人都闪闪发光。这就是苗族人的骄傲。', JSON_ARRAY(25), 'http://localhost:3000/src/views/community/topics_photos/苗族服饰搭配.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(5, '苗医苗药，大自然的馈赠', '走进苗医诊所，看医生用传统方法给患者治疗。那些草药，那些古老的医术，在这里依然闪闪发光。原来，最好的医生，就是大自然。', JSON_ARRAY(26), 'http://localhost:3000/src/views/community/topics_photos/苗医苗药探秘.jpg', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(1, '乌东村的慢生活', '村子里没有城市的喧嚣，只有鸟叫和风声。沿着山路走，看农民在田里劳作，这是最真实的贵州。', JSON_ARRAY(27), 'https://source.unsplash.com/800x600/?village,guizhou', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(2, '古茶树下的时光', '百年古茶树见证了多少岁月更替，采茶的阿姐们在树下唱着古老的采茶歌。这里的茶叶香气馥郁，一口就能尝出山野的味道。', JSON_ARRAY(28), 'https://source.unsplash.com/800x600/?ancient-tea,tea-culture', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(3, '鼓藏节，敬祖先的盛典', '整个寨子都在为鼓藏节忙碌，杀猪宰牛，准备着对祖先的敬礼。鼓声响起，全寨人都跪下了，这一刻，我感受到了什么叫信仰。', JSON_ARRAY(29), 'https://source.unsplash.com/800x600/?festival,ceremony', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(4, '苗寨手工艺品的灵魂', '竹编、木雕、银饰，每一件都是工匠几十年手艺的结晶。买回一件，就像买回了一段苗族的历史。', JSON_ARRAY(30), 'https://source.unsplash.com/800x600/?handicraft,art', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW()),
(5, '镜头下的苗族民俗', '用相机记录苗族人的日常，记录他们的笑容、劳作和庆祝。每一张照片都是一个故事，每一个故事都值得被记住。', JSON_ARRAY(31), 'https://source.unsplash.com/800x600/?folk-photography,portrait', FLOOR(RAND() * 500) + 100, FLOOR(RAND() * 100) + 20, FLOOR(RAND() * 50) + 5, 1, 1, DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 7) DAY), NOW());

-- 为15篇游记插入图片记录
INSERT INTO note_post_image (post_id, image_url, sort, create_time, update_time)
SELECT id, cover, 1, NOW(), NOW() FROM note_post WHERE id > (SELECT MAX(id) - 15 FROM note_post);
